name = "cloudflaredb-pages"
main = "worker.js"
{
  "compatibility_date": "2025-08-25",
  "compatibility_flags": ["global_fetch_strictly_public"]
}

[durable_objects]
bindings = [
  { name = "MyDatabase", class_name = "MyDatabase" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["MyDatabase"]
